display_name: PonyNotes
icon: linux/packaging/assets/logo.png
group: Applications/Office
vendor: PonyNotes
packager: PonyNotes
packagerEmail: support@appflowy.io
license: APGL-3.0
url: https://github.com/AppFlowy-IO/appflowy

build_arch: x86_64

keywords:
  - PonyNotes
  - Office
  - Document
  - Database
  - Note
  - Kanban
  - Note

generic_name: PonyNotes

categories:
  - Office
  - Productivity

startup_notify: true

supportedMimeType: x-scheme-handler/appflowy-flutter

requires:
  - libnotify
  - keybinder
