display_name: PonyNotes
package_name: appflowy

maintainer:
  name: PonyNotes
  email: support@appflowy.io

keywords:
  - PonyNotes
  - Office
  - Document
  - Database
  - Note
  - Kanban
  - Note

installed_size: 100000
icon: linux/packaging/assets/logo.png

generic_name: PonyNotes

categories:
  - Office
  - Productivity

startup_notify: true
essential: false

section: x11
priority: optional

supportedMimeType: x-scheme-handler/appflowy-flutter

dependencies:
  - libnotify-bin
  - libkeybinder-3.0-0
