[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]

[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-miphoneos-version-min=12.0", "-C", "link-arg=-Wl,-undefined,dynamic_lookup"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-arg=-mios-simulator-version-min=12.0", "-C", "link-arg=-Wl,-undefined,dynamic_lookup"]

[env]
CARGO_FEATURE_NO_NEON = "1"
